language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
matrix:
  allow_failures:
    - python: "3.5"
    - python: "nightly"
install: "pip install -r requirements.txt"
script: "./test.sh"
